import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/character.module.css'
import {useEffect, useState} from "react";
import {useRouter} from "next/router";

export default function Home() {
    const router = useRouter()
    return (
        <div className={styles.container}
             style={{backgroundImage: `url(${require("/public/character/bg.png").default.src})`}}>
            <Head>
                <title>角色选择</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.icons}>
                <img src={require("/public/character/icons.png").default.src} alt="s" className={styles.iconsimg}/>
            </div>
            <div className={styles.acontainer}>
                <img src={require("/public/character/contaner.png").default.src} alt="s" className={styles.iconsimg}/>
                <div className={styles.mancontainers}>
                    <img src={require("/public/character/g-1.png").default.src} alt="s" className={styles.mancard}
                         onClick={() => {
                             router.push("/mission")
                         }
                         }/>
                    <img src={require("/public/character/g-2.png").default.src} alt="s" className={styles.mancard}
                         onClick={() => {
                             router.push("/mission")
                         }
                         }/>
                    <img src={require("/public/character/g-3.png").default.src} alt="s" className={styles.mancard}
                         onClick={() => {
                             router.push("/mission")
                         }
                         }/>
                </div>
            </div>
        </div>
    )
}
