import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/bag.module.css'
import {useRouter} from "next/router";

export default function Home() {
    const router = useRouter()
    return (
        <div className={styles.container}
             style={{backgroundImage: `url(${require("/public/character/bg.png").default.src})`}}>
            <Head>
                <title>我的行囊</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.nav}>
                <img src={require("/public/mission/navbg.png").default.src} alt={"a"} className={styles.navbg}/>
                <div className={styles.nav2}>
                    <div className={styles.btn1} onClick={()=>{router.push("/mission")}}>
                        <img src={require("/public/mission/off-1.png").default.src} alt={"a"} className={styles.navbg}/>

                    </div>
                    <div className={styles.btn2} onClick={()=>{router.push("/map")}}>
                        <img src={require("/public/mission/off-2.png").default.src} alt={"a"} className={styles.navbg}/>

                    </div>
                    <div className={styles.btn3} onClick={()=>{router.push("/bag")}}>
                        <img src={require("/public/mission/on-3.png").default.src} alt={"a"} className={styles.navbg}/>

                    </div>
                    <div className={styles.btn4} onClick={()=>{router.push("/characterDetail")}}>
                        <img src={require("/public/mission/off-4.png").default.src} alt={"a"} className={styles.navbg}/>

                    </div>
                </div>
            </div>
        </div>
    )
}
