import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useRouter} from "next/router";

export default function Home() {
    const router = useRouter()
    return (<div className={styles.container}
                 style={{backgroundImage: `url(${require("/public/home/hpb.png").default.src})`}}>
            <Head>
                <title>玉琮迷踪</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.bg}>
                {/*<Image src={require("/public/home/hpb.png")} alt={"hpb"}/>*/}
            </div>
            <div className={styles.card}
                 style={{backgroundImage: `url(${require("/public/home/diwen.png").default.src})`}}>
                <div className={styles.cardimg}>
                    <Image src={require("/public/home/cardel.png")} alt={"sd"} width={176}
                           height={126}/>
                </div>
                <div className={styles.text}>
                    五千年前的良渚古国，为了即将到来的祭天大典，良渚国王在玉器匠人那里定制了一批用来祭祀的玉器，其中有一块耗时最久、地位最高的玉琮王不慎遗失。为了查出真相，找到玉琮完成祭天大典，良渚王下令：找到玉琮，便赐予来自良渚王室的神秘大礼。为此，良渚王城内掀起一股寻物之风，无论是神秘的祭祀、城外打猎的猎人、郊外播种的农民，抑或是精雕细琢的匠人都加入了此行列，在当时称为“玉琮迷踪”。
                </div>
            </div>

            <div className={styles.navbar}>
                <Image src={require("/public/home/nbar.png")} alt={"hpb"}/>
                <div className={styles.button1}>
                    <Image src={require("/public/home/pitch on-hp.png")} alt={"d"}/>
                </div>
                <div className={styles.button2} onClick={() => {
                    router.push("/my")
                }}>
                    <Image src={require("/public/home/unselected-my.png")} alt={"d"}/>
                </div>
                <div className={styles.begin}>
                    <div className={styles.link} onClick={() => {
                        router.push("/face")
                    }}></div>
                </div>
            </div>
        </div>)
}
