import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/my.module.css'
import {useRouter} from "next/router";

export default function Home() {
    const router = useRouter()
    return (
        <div className={styles.container}>
            <Head>
                <title>玉琮迷踪</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.bg}>
                <Image src={require("/public/my/bg-my.png")} alt={"bg"}/>
            </div>

            <div className={styles.navbar}>
                <Image src={require("/public/home/nbar.png")} alt={"hpb"}/>
                <div className={styles.button1} onClick={() => {
                    router.push("/")
                }}>
                    <Image src={require("/public/home/unselected-hp.png")} alt={"d"}/>
                </div>
                <div className={styles.button2} >
                    <Image src={require("/public/home/pitch on-my.png")} alt={"d"}/>
                </div>
                <div className={styles.begin}>
                    <div className={styles.link} onClick={()=>{
                        router.push("/face")
                    }}></div>
                </div>
            </div>
        </div>
    )
}
